//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTag
    {
        public System.Guid ID { get; set; }
        public System.Guid QuestionID { get; set; }
        public int TagID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
