#include "ClassList.h"
#include <iostream>
using namespace std;
const unsigned int MAX_NUM = 5;

int main() {
  
  Student students[MAX_NUM+1]; //Student information is provided by the user via keyboard
  ClassList BLG252E(MAX_NUM); // Has an empty array of Student objects

  for(int i= 0; i < MAX_NUM+1; i++)
	if (!BLG252E.insert(students[i]))
		cout << "Inserting the student info is failed" << endl;
  
  cout << "*****************************************" << endl;
  //Listing all students in the class
  BLG252E.printAll();
    cout << "*****************************************" << endl;
  //A new object is generated by copying the contents of another object
  ClassList BLG312 = BLG252E;
  cout << "*****************************************" << endl;  
  int search_id;
  //Finding the student with the id given by the user
  cout << "Searching for a student in the class BLG252E.." << endl
       << "id: "; cin >> search_id;

  Student* s1 = BLG252E.find(search_id);
  if (s1 != NULL){
	s1->print();
	s1->setSurname("New Surname");
  }
  else cout << "Student does not exist in the class " << endl;
  cout << "*****************************************" << endl;
  BLG252E.printAll();
  cout << "*****************************************" << endl;
  //New class is listed on the screen
  BLG312.printAll();
 
  return 0;
}
